services:
  mosquitto:
    image: eclipse-mosquitto:latest
    container_name: mosquitto
    restart: unless-stopped
    ports:
      - "1883:1883"
    volumes:
      - /home/fs/projects/mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - /mnt/data/mosquitto/config/passwd:/mosquitto/config/passwd
      - /mnt/data/mosquitto/data:/mosquitto/data
      - /mnt/data/mosquitto/log:/mosquitto/log
