services:

  db_recipes:
    image: postgres:16-alpine
    container_name: tandoor-db
    restart: unless-stopped
    volumes:
      - /mnt/data/tandoor/postgresql:/var/lib/postgresql/data
    env_file:
      - .env

  web_recipes:
    image: vabene1111/recipes:latest
    container_name: tandoor-web
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - /mnt/data/tandoor/mediafiles:/opt/recipes/mediafiles
      - staticfiles:/opt/recipes/staticfiles
      - nginx_config:/opt/recipes/nginx/conf.d
      - socket:/tmp/                      # ← neu
    depends_on:
      - db_recipes

  nginx_recipes:
    image: nginx:stable-alpine
    container_name: tandoor-nginx
    restart: unless-stopped
    ports:
      - "8700:80"
    volumes:
      - /home/fs/projects/tandoor/nginx/recipes.conf:/etc/nginx/conf.d/recipes.conf:ro
      - staticfiles:/static:ro
      - /mnt/data/tandoor/mediafiles:/media:ro
      - socket:/tmp/                      # ← neu: dasselbe Volume
    depends_on:
      - web_recipes
    command: /bin/sh -c "rm -f /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"


volumes:
  staticfiles:
  nginx_config:
  socket:                                 # ← neu: Volume-Deklaration
